apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoproj-blue
  labels:
    app: argoproj
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argoproj
      color: blue
  template:
    metadata:
      labels:
        app: argoproj
        color: blue
    spec:
      containers:
      - name: argoproj
        image: alexmt/rollouts-demo:blue
        ports:
        - containerPort: 80