apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoproj-green
  labels:
    app: argoproj
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argoproj
      color: green
  template:
    metadata:
      labels:
        app: argoproj
        color: green
    spec:
      containers:
      - name: argoproj
        image: alexmt/rollouts-demo:green
        ports:
        - containerPort: 80