apiVersion: v1
kind: Service
metadata:
  name: argoproj
spec:
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    color: blue
